import type { Metadata } from "next";
import "./globals.css";
import Banner from "@/components/Banner";
import Footer from "@/components/Footer";
import Header from "@/components/Header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="outfit">
        <Banner />
        <Header />
        <div className="mt-[70px] px-[16px]">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
