export const NewArrivalDataconst = [
  {
    id: 1,
    imgSrc:
      "https://cdn.pixabay.com/photo/2016/12/06/09/30/blank-1886001_1280.png",
    title: "Classic White T-Shirt",
    rating: 4.3,
    price: 150,
  },
  {
    id: 2,
    imgSrc:
      "https://cdn.pixabay.com/photo/2016/12/06/09/31/blank-1886008_1280.png",
    title: "Striped Summer Tee",
    rating: 4.7,
    price: 180,
  },
  {
    id: 3,
    imgSrc:
      "https://cdn.pixabay.com/photo/2016/08/15/19/57/red-devils-1596355_640.jpg",
    title: "Vintage Graphic Tee",
    rating: 4.5,
    price: 220,
  },
  {
    id: 4,
    imgSrc: "path/to/image4.jpg",
    title: "Plain Black T-Shirt",
    rating: 4.1,
    price: 130,
  },
  {
    id: 5,
    imgSrc: "path/to/image5.jpg",
    title: "Casual Blue Tee",
    rating: 4.6,
    price: 160,
  },
  {
    id: 6,
    imgSrc: "path/to/image6.jpg",
    title: "Graphic Print Tee",
    rating: 4.8,
    price: 200,
  },
  {
    id: 7,
    imgSrc: "path/to/image7.jpg",
    title: "Sporty Grey T-Shirt",
    rating: 4.2,
    price: 140,
  },
  {
    id: 8,
    imgSrc: "path/to/image8.jpg",
    title: "Retro Color Block Tee",
    rating: 4.4,
    price: 210,
  },
  {
    id: 9,
    imgSrc: "path/to/image9.jpg",
    title: "Eco-friendly Green Tee",
    rating: 4.9,
    price: 230,
  },
  {
    id: 10,
    imgSrc: "path/to/image10.jpg",
    title: "Fitted Black Tee",
    rating: 4.0,
    price: 120,
  },
  {
    id: 11,
    imgSrc: "path/to/image11.jpg",
    title: "Loose Fit Red Tee",
    rating: 4.3,
    price: 170,
  },
  {
    id: 12,
    imgSrc: "path/to/image12.jpg",
    title: "V-Neck White Tee",
    rating: 4.6,
    price: 180,
  },
  {
    id: 13,
    imgSrc: "path/to/image13.jpg",
    title: "Bold Yellow T-Shirt",
    rating: 4.2,
    price: 190,
  },
  {
    id: 14,
    imgSrc: "path/to/image14.jpg",
    title: "Classic Blue Tee",
    rating: 4.7,
    price: 160,
  },
  {
    id: 15,
    imgSrc: "path/to/image15.jpg",
    title: "Urban Style Tee",
    rating: 4.5,
    price: 210,
  },
  {
    id: 16,
    imgSrc: "path/to/image16.jpg",
    title: "Striped Black and White Tee",
    rating: 4.8,
    price: 200,
  },
  {
    id: 17,
    imgSrc: "path/to/image17.jpg",
    title: "Minimalist Grey Tee",
    rating: 4.1,
    price: 140,
  },
  {
    id: 18,
    imgSrc: "path/to/image18.jpg",
    title: "Cotton Casual Tee",
    rating: 4.4,
    price: 160,
  },
  {
    id: 19,
    imgSrc: "path/to/image19.jpg",
    title: "Trendy Pink Tee",
    rating: 4.9,
    price: 220,
  },
  {
    id: 20,
    imgSrc: "path/to/image20.jpg",
    title: "Bold Statement Tee",
    rating: 4.0,
    price: 130,
  },
];

export const topSellingData = [
  {
    id: 1,
    imgSrc: "path/to/image1.jpg",
    title: "Premium Leather Jacket",
    rating: 4.9,
    price: 350,
  },
  {
    id: 2,
    imgSrc: "path/to/image2.jpg",
    title: "Classic Denim Jacket",
    rating: 4.7,
    price: 250,
  },
  {
    id: 3,
    imgSrc: "path/to/image3.jpg",
    title: "Slim Fit Chinos",
    rating: 4.8,
    price: 180,
  },
  {
    id: 4,
    imgSrc: "path/to/image4.jpg",
    title: "Casual Sneakers",
    rating: 4.6,
    price: 120,
  },
  {
    id: 5,
    imgSrc: "path/to/image5.jpg",
    title: "Wool Blend Coat",
    rating: 4.9,
    price: 400,
  },
  {
    id: 6,
    imgSrc: "path/to/image6.jpg",
    title: "Running Shoes",
    rating: 4.5,
    price: 150,
  },
  {
    id: 7,
    imgSrc: "path/to/image7.jpg",
    title: "Designer Sunglasses",
    rating: 4.7,
    price: 220,
  },
  {
    id: 8,
    imgSrc: "path/to/image8.jpg",
    title: "Formal Dress Shoes",
    rating: 4.8,
    price: 200,
  },
  {
    id: 9,
    imgSrc: "path/to/image9.jpg",
    title: "Luxury Wristwatch",
    rating: 4.9,
    price: 500,
  },
  {
    id: 10,
    imgSrc: "path/to/image10.jpg",
    title: "Elegant Silk Scarf",
    rating: 4.6,
    price: 80,
  },
  {
    id: 11,
    imgSrc: "path/to/image11.jpg",
    title: "Comfortable Hoodie",
    rating: 4.7,
    price: 130,
  },
  {
    id: 12,
    imgSrc: "path/to/image12.jpg",
    title: "Classic Polo Shirt",
    rating: 4.5,
    price: 100,
  },
  {
    id: 13,
    imgSrc: "path/to/image13.jpg",
    title: "Leather Messenger Bag",
    rating: 4.8,
    price: 260,
  },
  {
    id: 14,
    imgSrc: "path/to/image14.jpg",
    title: "Stylish Trench Coat",
    rating: 4.9,
    price: 420,
  },
  {
    id: 15,
    imgSrc: "path/to/image15.jpg",
    title: "Sporty Windbreaker",
    rating: 4.6,
    price: 180,
  },
  {
    id: 16,
    imgSrc: "path/to/image16.jpg",
    title: "Casual Backpack",
    rating: 4.7,
    price: 150,
  },
  {
    id: 17,
    imgSrc: "path/to/image17.jpg",
    title: "Elegant Blouse",
    rating: 4.8,
    price: 90,
  },
  {
    id: 18,
    imgSrc: "path/to/image18.jpg",
    title: "Classic Leather Belt",
    rating: 4.5,
    price: 60,
  },
  {
    id: 19,
    imgSrc: "path/to/image19.jpg",
    title: "Waterproof Jacket",
    rating: 4.6,
    price: 240,
  },
  {
    id: 20,
    imgSrc: "path/to/image20.jpg",
    title: "Luxury Handbag",
    rating: 4.9,
    price: 450,
  },
];
